config/routes.rb
Hrmff::Application.routes.draw do
  
  resources :app_roles

  resources :employees

  resources :roles

  resources :relations

  resources :airlines

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  
  match 'employees/show_for_company/:id', :controller=>'employees', :action => 'show_for_company'
  
  resources :employees do
    member do
      get 'disable'
      get 'enable'
    end
  end
  

  root :to => 'employees#index'

end

app/models/role.rb
class Role < ActiveRecord::Base
  	attr_accessible :code, :name

  	before_save { |role| role.code = code.upcase }

  	validates :code, presence: true, uniqueness: { case_sensitive: false }
  	validates :name, presence: true
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
    before_filter :check_access

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table class="pretty">
  <tr>
    <td>
      <div class="field">
        <%= f.label :code %><br />
        <%= f.text_field :code %>
      </div>
    </td>
  </tr>
  <tr>
    <td>
      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </div>
    </td>
  </tr>
</table>
  <div class="actions">
    <%= link_to 'Back', roles_path %>
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

app/views/roles/index.html.erb
<table class="pretty">
  <caption> 
    Roles <%= link_to image_tag("/images/add.png", :border => 0, :width => 30, :height => 30, :align => "right"), new_role_path%>
</caption>
  <tr>
    <th>Code</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roles.each do |role| %>
  <tr>
    <td><%= role.code %></td>
    <td><%= role.name %></td>
    <td><%= link_to image_tag("/images/info.png", :border => 0, :width => 16, :height => 16), role %></td>
    <td><%= link_to image_tag("/images/edit.png", :border => 0, :width => 16, :height => 16), edit_role_path(role) %></td>
    <td><%= link_to image_tag("/images/delete.png", :border => 0, :width => 16, :height => 16), role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>
<table class="pretty">
	<tr>
		<td>
			<p>
			  <b>Code:</b>
			  <%= @role.code %>
			</p>
		</td>
	</tr>
	<tr>
		<td>
			<p>
			  <b>Name:</b>
			  <%= @role.name %>
			</p>
		</td>
	</tr>
</table>

<div class="actions">
	<%= link_to 'Edit', edit_role_path(@role) %> |
	<%= link_to 'Back', roles_path %>
</div>