config/routes.rb
Hrmff::Application.routes.draw do
  
  resources :app_roles

  resources :employees

  resources :roles

  resources :relations

  resources :airlines

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  
  match 'employees/show_for_company/:id', :controller=>'employees', :action => 'show_for_company'
  
  resources :employees do
    member do
      get 'disable'
      get 'enable'
    end
  end
  

  root :to => 'employees#index'

end

app/models/airline.rb
class Airline < ActiveRecord::Base
  has_many :users
  has_many :employees
  
  attr_accessible :code, :description, :enabled, :name
  validates :code, presence: true, uniqueness: { case_sensitive: false }
  validates :description, presence: true
  validates :enabled, presence: true
  validates :name , presence: true
end

app/controllers/airlines_controller.rb
class AirlinesController < ApplicationController
    before_filter :check_access
    

  # GET /airlines
  # GET /airlines.json
  def index
    @airlines = Airline.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @airlines }
    end
  end

  # GET /airlines/1
  # GET /airlines/1.json
  def show
    @airline = Airline.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @airline }
    end
  end

  # GET /airlines/new
  # GET /airlines/new.json
  def new
    @airline = Airline.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @airline }
    end
  end

  # GET /airlines/1/edit
  def edit
    @airline = Airline.find(params[:id])
  end

  # POST /airlines
  # POST /airlines.json
  def create
    @airline = Airline.new(params[:airline])

    respond_to do |format|
      if @airline.save
        format.html { redirect_to @airline, notice: 'Airline was successfully created.' }
        format.json { render json: @airline, status: :created, location: @airline }
      else
        format.html { render action: "new" }
        format.json { render json: @airline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /airlines/1
  # PUT /airlines/1.json
  def update
    @airline = Airline.find(params[:id])

    respond_to do |format|
      if @airline.update_attributes(params[:airline])
        format.html { redirect_to @airline, notice: 'Airline was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @airline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airlines/1
  # DELETE /airlines/1.json
  def destroy
    @airline = Airline.find(params[:id])
    @airline.destroy

    respond_to do |format|
      format.html { redirect_to airlines_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/airlines_helper.rb
module AirlinesHelper
end

app/views/airlines/_form.html.erb
<%= form_for(@airline) do |f| %>
  <% if @airline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@airline.errors.count, "error") %> prohibited this airline from being saved:</h2>
      <ul>
      <% @airline.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table class="pretty">
  <tr>
    <td>      
      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :code %><br />
        <%= f.text_field :code %>
      </div>
    </td>
  </tr>
  <tr>
    <td>
      <div class="field">
        <%= f.label :description %><br />
        <%= f.text_area :description %>
      </div>
    </td>
  </tr>
</table>
  <div class="actions">
    <%= link_to 'Back', airlines_path %>
    <%= f.submit %>
  </div>
<% end %>

app/views/airlines/edit.html.erb
<h1>Editing airline</h1>

<%= render 'form' %>

app/views/airlines/index.html.erb
<table class="pretty">
  <caption>Airlines <%= link_to image_tag("/images/add.png", :border => 0, :width => 30, :height => 30, :align => "right"), new_airline_path %>
  </caption>
  <tr>
    <th>Name</th>
    <th>Code</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @airlines.each do |airline| %>
  <tr>
    <td><%= airline.name %></td>
    <td><%= airline.code %></td>
    <td><%= airline.description %></td>
    <td><%= link_to image_tag("/images/info.png", :border => 0, :width => 16, :height => 16), airline %></td>
    <td><%= link_to image_tag("/images/edit.png", :border => 0, :width => 16, :height => 16), edit_airline_path(airline) %></td>
    <td><%= link_to image_tag("/images/delete.png", :border => 0, :width => 16, :height => 16), airline, method: :delete, data: { confirm: 'Are you sure? All dependents will also be removed!' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/airlines/new.html.erb
<h1>New airline</h1>

<%= render 'form' %>

app/views/airlines/show.html.erb
<p id="notice"><%= notice %></p>
<table class="pretty">
	<tr>
		<td>
			<p>
			  <b>Name:</b>
			  <%= @airline.name %>
			</p>
			<p>
			  <b>Code:</b>
			  <%= @airline.code %>
			</p>
		</td>
	</tr>
	<tr>
		<td>
			<p>
			  <b>Description:</b>
			  <%= @airline.description %>
			</p>
		</td>
	</tr>
</table>
<div class="actions">
	<%= link_to 'Edit', edit_airline_path(@airline) %> |
	<%= link_to 'Back', airlines_path %>
</div>