config/routes.rb
Hrmff::Application.routes.draw do
  
  resources :app_roles

  resources :employees

  resources :roles

  resources :relations

  resources :airlines

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  
  match 'employees/show_for_company/:id', :controller=>'employees', :action => 'show_for_company'
  
  resources :employees do
    member do
      get 'disable'
      get 'enable'
    end
  end
  

  root :to => 'employees#index'

end

app/models/app_role.rb
class AppRole < ActiveRecord::Base
  has_many :users
  
  attr_accessible :code, :description
end

app/controllers/app_roles_controller.rb
class AppRolesController < ApplicationController
    before_filter :check_access

  # GET /app_roles
  # GET /app_roles.json
  def index
    @app_roles = AppRole.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @app_roles }
    end
  end

  # GET /app_roles/1
  # GET /app_roles/1.json
  def show
    @app_role = AppRole.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @app_role }
    end
  end

  # GET /app_roles/new
  # GET /app_roles/new.json
  def new
    @app_role = AppRole.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @app_role }
    end
  end

  # GET /app_roles/1/edit
  def edit
    @app_role = AppRole.find(params[:id])
  end

  # POST /app_roles
  # POST /app_roles.json
  def create
    @app_role = AppRole.new(params[:app_role])

    respond_to do |format|
      if @app_role.save
        format.html { redirect_to @app_role, notice: 'App role was successfully created.' }
        format.json { render json: @app_role, status: :created, location: @app_role }
      else
        format.html { render action: "new" }
        format.json { render json: @app_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /app_roles/1
  # PUT /app_roles/1.json
  def update
    @app_role = AppRole.find(params[:id])

    respond_to do |format|
      if @app_role.update_attributes(params[:app_role])
        format.html { redirect_to @app_role, notice: 'App role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @app_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_roles/1
  # DELETE /app_roles/1.json
  def destroy
    @app_role = AppRole.find(params[:id])
    @app_role.destroy

    respond_to do |format|
      format.html { redirect_to app_roles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/app_roles_helper.rb
module AppRolesHelper
end

app/views/app_roles/_form.html.erb
<%= form_for(@app_role) do |f| %>
  <% if @app_role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app_role.errors.count, "error") %> prohibited this app_role from being saved:</h2>

      <ul>
      <% @app_role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/app_roles/edit.html.erb
<h1>Editing app_role</h1>

<%= render 'form' %>

<%= link_to 'Show', @app_role %> |
<%= link_to 'Back', app_roles_path %>

app/views/app_roles/index.html.erb
<h1>Listing app_roles</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @app_roles.each do |app_role| %>
  <tr>
    <td><%= app_role.code %></td>
    <td><%= app_role.description %></td>
    <td><%= link_to 'Show', app_role %></td>
    <td><%= link_to 'Edit', edit_app_role_path(app_role) %></td>
    <td><%= link_to 'Destroy', app_role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New App role', new_app_role_path %>

app/views/app_roles/new.html.erb
<h1>New app_role</h1>

<%= render 'form' %>

<%= link_to 'Back', app_roles_path %>

app/views/app_roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @app_role.code %>
</p>

<p>
  <b>Description:</b>
  <%= @app_role.description %>
</p>


<%= link_to 'Edit', edit_app_role_path(@app_role) %> |
<%= link_to 'Back', app_roles_path %>